=== AGINFRA-PLUS/skos-play/fr.sparna/rdf/skos/skos-printer/src/main/resources/thesaurus-display.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.sparna.fr/thesaurus-display" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:disp="http://www.sparna.fr/thesaurus-display">


    <element name="before" type="string"></element>

    <element name="after" type="string"></element>

    <element name="word" type="string"></element>

    <complexType name="permutation">
        <sequence maxOccurs="1" minOccurs="1">
    		<element ref="disp:before"></element>
    		<element ref="disp:word"></element>
    		<element ref="disp:after"></element>
    	</sequence>
    	<attribute ref="disp:conceptId"></attribute>
    </complexType>
    
    <element name="permutation" type="disp:permutation"></element>

    <attribute name="conceptId" type="anyURI"></attribute>

    <complexType name="permuted">
    	<sequence maxOccurs="unbounded">
    		<element ref="disp:permutation"></element>
    	</sequence>
    </complexType>

    <element name="permuted" type="disp:permuted"></element>

    <complexType name="conceptRef">
    	<sequence>
    		<element ref="disp:label"></element>
    	</sequence>
    	<attribute ref="disp:type" use="optional"></attribute>
    	<attribute ref="disp:conceptId"></attribute>
    </complexType>

    <element name="label" type="string"></element>

    <attribute name="type">
    	<simpleType>
    		<restriction base="string">
    			<enumeration value="pref"></enumeration>
    			<enumeration value="alt"></enumeration>
    		</restriction>
    	</simpleType>
    </attribute>

    <complexType name="term">
        <annotation>
        	<documentation>Should be a reference to a conceptGroup - not handled for the moment</documentation>
        </annotation>
        <complexContent>
    		<extension base="disp:conceptRef">

    			<sequence>
    				<element ref="disp:CC" maxOccurs="unbounded"
    					minOccurs="0">
    				</element>
    				<element ref="disp:SN" minOccurs="0"
    					maxOccurs="unbounded">
    				</element>
    				<element ref="disp:UF" minOccurs="0"
    					maxOccurs="unbounded">
    				</element>
    				<element ref="disp:TT" minOccurs="0"
    					maxOccurs="unbounded">
    				</element>
    				<element ref="disp:BT" minOccurs="0"
    					maxOccurs="unbounded">
    				</element>
    				<element ref="disp:NT" minOccurs="0"
    					maxOccurs="unbounded">
    				</element>
    				<element ref="disp:RT" minOccurs="0"
    					maxOccurs="unbounded">
    				</element>
    				<element ref="disp:DEF" minOccurs="0"
    					maxOccurs="unbounded">
    				</element>
    				<element ref="disp:HN" minOccurs="0"
    					maxOccurs="unbounded">
    				</element>
    				<element ref="disp:SC" minOccurs="0" maxOccurs="1"></element>
    				<element ref="disp:USE" minOccurs="0" maxOccurs="1"></element>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType>
    
    <element name="CC" type="string"></element>

    <element name="SN" type="string">
    	<annotation>
    		<documentation>A concept scope note</documentation>
    	</annotation></element>

    <element name="UF" type="string">
    	<annotation>
    		<documentation>A synonyme of a concept</documentation>
    	</annotation></element>

    <complexType name="conceptRefField">
    	<sequence>
    		<element ref="disp:term"></element>
    	</sequence>
    </complexType>
    
    <element name="term" type="disp:conceptRef"></element>

    <element name="TT" type="disp:conceptRefField">
    	<annotation>
    		<documentation>Reference to the top concept of a concept</documentation>
    	</annotation></element>

    <element name="BT" type="disp:conceptRefField">
    	<annotation>
    		<documentation>Reference to a broader concept</documentation>
    	</annotation></element>

    <element name="NT" type="disp:conceptRefField">
    	<annotation>
    		<documentation>Reference to  a concept narrower term</documentation>
    	</annotation></element>

    <element name="RT" type="disp:conceptRefField">
    	<annotation>
    		<documentation>Reference to a concept related term</documentation>
    	</annotation></element>

    <element name="DEF" type="string">
    	<annotation>
    		<documentation>A concept definition</documentation>
    	</annotation></element>

    <element name="HN" type="string">
    	<annotation>
    		<documentation>A concept history note</documentation>
    	</annotation></element>


    <element name="USE" type="disp:conceptRefField">
    	<annotation>
    		<documentation>The reference to the preferred term of a concept</documentation>
    	</annotation></element>

    <element name="SC" type="string">
    	<annotation>
    		<documentation></documentation>
    	</annotation></element>

    <complexType name="alphabeticalDisplay">
    	<sequence>
    		<element name="term" type="disp:term" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="display">
    	<sequence>
    		<element ref="disp:header" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<choice minOccurs="1" maxOccurs="1">
    			<element ref="disp:alphabetical"></element>
    			<element ref="disp:hierarchical"></element>
                <element ref="disp:permuted"></element>
            </choice>
    	</sequence>
    </complexType>

    <element name="alphabetical" type="disp:alphabeticalDisplay"></element>

    <complexType name="displayHeader">
    	<sequence>
    		<element name="title" type="string"></element>
    		<element name="date" type="dateTime"></element>
    	</sequence>
    </complexType>

    <element name="header" type="disp:displayHeader"></element>

    <complexType name="hierarchicalDisplay"></complexType>

    <element name="hierarchical" type="disp:hierarchicalDisplay"></element>

    <element name="display" type="disp:display"></element>
</schema>

=== AGINFRA-PLUS/skos-play/fr.sparna/rdf/skos-printer/src/main/resources/thesaurus-display.xml
<?xml version="1.0" encoding="UTF-8"?>
<disp:display xmlns:disp="http://www.sparna.fr/thesaurus-display" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sparna.fr/thesaurus-display thesaurus-display.xsd ">
  <disp:header>
    <disp:title>disp:title</disp:title>
    <disp:date>2001-12-31T12:00:00</disp:date>
  </disp:header>
  <disp:alphabetical>
    <disp:term disp:conceptId="http://tempuri.org" disp:type="pref">
      <disp:label>disp:label</disp:label>
      <disp:CC>disp:CC</disp:CC>
      <disp:SN>disp:SN</disp:SN>
      <disp:UF>disp:UF</disp:UF>
      <disp:TT>
        <disp:term disp:conceptId="http://tempuri.org" disp:type="pref">
          <disp:label>disp:label</disp:label>
        </disp:term>
      </disp:TT>
      <disp:BT>
        <disp:term disp:conceptId="http://tempuri.org" disp:type="pref">
          <disp:label>disp:label</disp:label>
        </disp:term>
      </disp:BT>
      <disp:NT>
        <disp:term disp:conceptId="http://tempuri.org" disp:type="pref">
          <disp:label>disp:label</disp:label>
        </disp:term>
      </disp:NT>
      <disp:RT>
        <disp:term disp:conceptId="http://tempuri.org" disp:type="pref">
          <disp:label>disp:label</disp:label>
        </disp:term>
      </disp:RT>
      <disp:DEF>disp:DEF</disp:DEF>
      <disp:HN>disp:HN</disp:HN>
      <disp:SC>disp:SC</disp:SC>
      <disp:USE>
        <disp:term disp:conceptId="http://tempuri.org" disp:type="pref">
          <disp:label>disp:label</disp:label>
        </disp:term>
      </disp:USE>
    </disp:term>
  </disp:alphabetical>
</disp:display>
